# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Authentication' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'login' do
    @driver.get('https://cloudvr.pythonanywhere.com/bank/login')
  #  @driver.manage.resize_to(1308, 720)
    @driver.find_element(:id, 'exampleInputUsername').click
    @driver.find_element(:id, 'exampleInputUsername').send_keys('tester')
    @driver.find_element(:id, 'exampleInputPassword').click
    @driver.find_element(:id, 'exampleInputPassword').send_keys('password@1234')
    @driver.find_element(:css, '.btn').click
  end
  it 'systemuser' do
    @driver.get('https://cloudvr.pythonanywhere.com/bank/about')
   # @driver.manage.resize_to(1308, 720)
    @driver.find_element(:css, '.nav-item:nth-child(6) span').click
    @driver.find_element(:link_text, 'System User List').click
  end
  it 'checktitle' do
    @driver.get('https://cloudvr.pythonanywhere.com/bank/login')
  #  @driver.manage.resize_to(1308, 720)
    @driver.find_element(:id, 'exampleInputUsername').click
    @driver.find_element(:css, '.h4').click
    expect(@driver.find_element(:css, '.h4').text).to eq('Welcome to Cloud Bank')
  end
end
